### ISSUE TITLE
Don't bundle binary files in the repository

### ISSUE THREAD

**Issue by adri326** [ToothedTomb/AreyouUsingArchLinux#1]
There is no telling what the binary file `areyouusingarch2.0` could do. It might be a genuine build of the project, but it might also be something malicious.

The presence of a random binary file on a poorly-known project should be enough of a tell to ward anyone who is security-minded off.

**Comment by ToothedTomb** [comment]
Howdy, I am 100% sure that the binary file is safe to run.
There is even code of the program in the GitHub repo.
I may just leave the binary file in the releases section and remove from the GitHub repo. Thanks.
Let me know if you got other issues. 

Jonathan Steadman  - Tech support / developer.

**Comment by abb3v** [comment]
> Howdy, I am 100% sure that the binary file is safe to run.

Even then, you aren't meant to track binary files to git. Thats why most people output to a `build/` directory and have it in your .gitignore. 

Best practice for including binary files on GitHub is through the [Releases ](https://github.com/ToothedTomb/AreyouUsingArchLinux/releases) section.

**Comment by ToothedTomb** [comment]
Thanks for your comment and the binary file has been removed thanks for your guys feedback. Now its going to be only in the releases section. :)
