### ISSUE TITLE
after running script leaves terminal blue

### ISSUE THREAD

**Issue by 4jss** [ToothedTomb/AreyouUsingArchLinux#4]
after running script with chmod +x are-you-using-arch-linux and doing ./are-you-using-arch-linux it passes as arch and leaves the terminal blue

**Comment by ToothedTomb** [comment]
I will have a look into this issue and find a solution.
Thanks Jonathan Steadman.

**Comment by ToothedTomb** [comment]
Hello looks like I was able to find a solution. Thanks for reporting this bug to me. 

Have a good week.

From Jonathan Steadman.
